build:
  image: golang:1.6
  environment:
    - CGO_ENABLED=0
    - GO15VENDOREXPERIMENT=1
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: ribase/drone-s3-sync
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: ribase/drone-s3-sync
    tag: develop
    when:
      branch: develop

plugin:
  name: S3 Sync
  desc: Sync a directory with an Amazon S3 Bucket
  type: publish
  image: ribase/drone-s3-sync
  labels:
    - publish
    - artifacts
    - amazon
    - aws
    - s3
