# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone S3 Sync" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release\drone-s3-sync.exe c:\drone-s3-sync.exe
ENTRYPOINT [ "c:\\drone-s3-sync.exe" ]
